// License Lens —— 首批登记样板：以本工程自身的产物与依赖为例
import type { RegistryState } from './types';

export const SEED_STATE: RegistryState = {
  products: [
    { id: 'prod_site', name: 'aurora-web 站点产物（dist）', kind: 'runtime' },
    { id: 'prod_build', name: '构建链（vite / tsc）', kind: 'development' },
  ],
  dependencies: [
    {
      id: 'dep_react',
      name: 'react',
      version: '18.3.1',
      introducedBy: 'npm dependencies',
      purpose: 'UI 视图层',
      license: 'MIT',
      kind: 'runtime',
      assignments: [{ productId: 'prod_site', path: 'src/main.tsx', scope: 'runtime' }],
    },
    {
      id: 'dep_react_dom',
      name: 'react-dom',
      version: '18.3.1',
      introducedBy: 'npm dependencies',
      purpose: 'React DOM 渲染器',
      license: 'MIT',
      kind: 'runtime',
      assignments: [{ productId: 'prod_site', path: 'src/main.tsx', scope: 'runtime' }],
    },
    {
      id: 'dep_lucide',
      name: 'lucide-react',
      version: '0.460.0',
      introducedBy: 'npm dependencies',
      purpose: '页面图标库',
      license: 'ISC',
      kind: 'runtime',
      assignments: [{ productId: 'prod_site', path: 'src/App.tsx', scope: 'runtime' }],
    },
    {
      id: 'dep_vite',
      name: 'vite',
      version: '5.4.8',
      introducedBy: 'npm devDependencies',
      purpose: '开发服务器与打包器',
      license: 'MIT',
      kind: 'development',
      assignments: [{ productId: 'prod_build', path: 'vite.config.ts', scope: 'development' }],
    },
    {
      id: 'dep_plugin_react',
      name: '@vitejs/plugin-react',
      version: '4.3.2',
      introducedBy: 'npm devDependencies',
      purpose: 'Vite 的 React 编译插件',
      license: 'MIT',
      kind: 'development',
      assignments: [{ productId: 'prod_build', path: 'vite.config.ts', scope: 'development' }],
    },
    {
      id: 'dep_tsc',
      name: 'typescript',
      version: '5.6.3',
      introducedBy: 'npm devDependencies',
      purpose: '类型检查与 .tsbuildinfo 生成',
      license: 'Apache-2.0',
      kind: 'development',
      assignments: [{ productId: 'prod_build', path: 'tsconfig.json', scope: 'development' }],
    },
    {
      id: 'dep_types_react',
      name: '@types/react',
      version: '18.3.11',
      introducedBy: 'npm devDependencies',
      purpose: 'React 类型声明（仅编译期）',
      license: 'MIT',
      kind: 'development',
      assignments: [{ productId: 'prod_build', path: 'tsconfig.app.json', scope: 'development' }],
    },
    {
      id: 'dep_types_react_dom',
      name: '@types/react-dom',
      version: '18.3.1',
      introducedBy: 'npm devDependencies',
      purpose: 'ReactDOM 类型声明（仅编译期）',
      license: 'MIT',
      kind: 'development',
      assignments: [{ productId: 'prod_build', path: 'tsconfig.app.json', scope: 'development' }],
    },
  ],
};
